spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase
    username: root
    password: NaVeEnKuMaR@290701


  liquibase:
        change-log: 'classpath:db/changelog/app-changelog.xml'
        default-schema: liquibase


  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: REDIS

  quartz:
    job-store-type: MEMORY
    properties:
        org:
            quartz:
            scheduler:
                instanceName: MyQuartzScheduler
            threadPool:
                threadCount: 5

  main:
    allow-bean-definition-overriding: true